/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#1a002e",
        "surface-dim": "#0f1524",
        "on-tertiary-fixed": "#1a002e",
        "secondary-fixed-dim": "#88b4cc",
        "on-secondary-fixed": "#0d1f2b",
        "on-tertiary-fixed-variant": "#4d2a73",
        "on-primary-container": "#c8eaff",
        "on-error": "#1a0000",
        "primary-container": "#0e4d6e",
        "surface-container-low": "#111828",
        "secondary-container": "#1a3a4e",
        "on-secondary-container": "#c0d8e8",
        "primary-fixed": "#c8eaff",
        "on-error-container": "#ffb3b3",
        "background": "#0a0e1a",
        "on-background": "#e0e8f0",
        "surface-container-high": "#1a2438",
        "inverse-on-surface": "#0a0e1a",
        "tertiary": "#c8a0f0",
        "primary": "#7dd3fc",
        "inverse-primary": "#0a4c6e",
        "surface-container": "#141c2e",
        "surface-container-highest": "#202c42",
        "on-tertiary-container": "#e8d0ff",
        "on-surface-variant": "#a0b4c4",
        "surface-variant": "#1a2438",
        "surface": "#0f1524",
        "secondary-fixed": "#c0d8e8",
        "tertiary-fixed": "#e8d0ff",
        "on-secondary": "#001f2e",
        "on-surface": "#e0e8f0",
        "inverse-surface": "#e0e8f0",
        "surface-bright": "#1a2438",
        "tertiary-fixed-dim": "#c8a0f0",
        "primary-fixed-dim": "#7dd3fc",
        "surface-tint": "#7dd3fc",
        "secondary": "#88b4cc",
        "on-primary": "#001f2e",
        "surface-container-lowest": "#0a0e1a",
        "error": "#ff6b6b",
        "outline": "#4a6070",
        "on-primary-fixed": "#001f2e",
        "on-secondary-fixed-variant": "#2a4a5e",
        "error-container": "#3d1414",
        "tertiary-container": "#3d2060",
        "outline-variant": "#2a3a48",
        "on-primary-fixed-variant": "#004d73"
      },
      fontFamily: {
        mono: ["JetBrains Mono", "monospace"],
        sans: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}